# This is a basic workflow to help you get started with Actions

name: Static analysis

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Android Lint
        run: ./gradlew lintDebug
      - name: Diktat
        run: ./gradlew diktatCheck
      - name: Detekt
        run: ./gradlew detekt